import type { Show } from "./types";

export const shows: Show[] = [
  {
    id: "s7",
    status: "upcoming",
    day: "18",
    month: "SEP",
    year: "2026",
    title: "KU Acoustic Open World",
    venue: "Chakkraphan Pensiri",
    time: "16:00-16:40",
    tag: "Full Band",
  },
  {
    id: "s8",
    status: "past",
    day: "03",
    month: "MAR",
    year: "2025",
    title: "KU Acoustic Wave of Vibes Concert",
    venue: "Kasetsart University Rugby Field",
    time: "16:00-21:00",
    tag: "Full Band",
    link: "https://www.youtube.com/live/GM2EAHC6cPk?si=Jz7PvuP4fHvnWleo",
  },
  {
    id: "s4",
    status: "past",
    day: "25",
    month: "FEB",
    year: "2026",
    title: "KU Acoustic Run In Rhythm Concert",
    venue: "Prasert Na Nagara Theatre",
    time: "16:30-20:30",
    tag: "Full Band",
    link: "https://www.youtube.com/live/ib7OgoWOZQ8",
  },
  {
    id: "s3",
    status: "past",
    day: "17",
    month: "JUL",
    year: "2026",
    title: "KU Acoustic Truck",
    venue: "KU Central Cafeteria 1",
    time: "17:00-18:00",
    tag: "Acoustic",
    link: "https://www.youtube.com/live/RTk2M66fQqY?si=GMVCsWPZgfqDOhNf",
  },
  {
    id: "s2",
    status: "past",
    day: "26",
    month: "JUL",
    year: "2026",
    title: "KU Acoustic FRESHY DAY FRESHY NIGHT",
    venue: "Insee Chantarasatit Stadium",
    time: "15:40-16:15",
    tag: "Full Band",
    link: "https://youtu.be/0EWAKp32uhI",
  },
  {
    id: "s1",
    status: "past",
    day: "09",
    month: "AUG",
    year: "2026",
    title: "KU Acoustic Royal Project",
    venue: "Central World",
    time: "18:00-20:00",
    tag: "Acoustic",
  },
];
